### ISSUE TITLE
proxy handler

### ISSUE THREAD

**Issue by ryanvoong** [UCLA-CS130/Team12#28]
Hi Team12,

We found two issues while trying to implement the proxy handler.

1. In `Server::session`, if the request uri is `/foo/bar/abc/def`, you currently only look for `/foo` (which is `req->uriHead()`) in the `uri2handler` map. This is incorrect, because a handler's path in the config may be `/foo/bar`. Therefore, you must check for all possible combinations in `uri2handler` and pick the handler with the longest matching uri prefix:
    - `/foo/bar/abc/def`
    - `/foo/bar/abc`
    - `/foo/bar`
    - `/foo`

2. The proxy handler will only work correctly if its path is set to `/` in the config. Currently, if the request uri is `/`, it will be changed to `/index` by `Request::uriHead` which is incorrect. It should be left as `/`.

Once these two issues are fixed, the proxy handler will work correctly.

Thanks!
spaceteam

**Comment by plantver** [comment]
Thank you for your post.
We are aware of this two issues. However these should not be critical issues that would interfere with the implementation of proxy server.
For now, if you wish to test the proxy handler, you can use set `"index"` to map to the proxy handler in the `get_server_parameters` function  in `server.cc`.

**Comment by ryanvoong** [comment]
The issues are still a problem because after the page is received, it will contain links to image, CSS, JS, and other files. The browser will send additional requests to get those files. For example, if it requests `/css/main.css`, the `Server::session` function will only try to look for the handler that `/css` maps to, instead of checking `/` to get the proxy handler. So all requests for the additional files will fail.

**Comment by plantver** [comment]
Are we supposed to set a fixed website to proxy to in the config file? For example:
`path / ProxyHander { ucla.edu; }`
We are changing the code to will allow `/` right now.

**Comment by ryanvoong** [comment]
Yes, the host must be defined. All requests to the proxy handler would be forwarded to that specific website. Here's an example of what the config for proxy handler would look like:
```
path / ProxyHandler {
	host www.ucla.edu;
	port 80;
}
```
So if the browser is requesting `/css/main.css`, we want to get `www.ucla.edu/css/main.css`.

Thanks for making the change!

**Comment by plantver** [comment]
Thanks. We are working on it.

**Comment by liuchang2872** [comment]
Hi Spaceteam, 

I think I have fixed the issue.
Please let us know if you have other issues :)

Thanks,
Chang
